[2023-11-26T01:26:01.876+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_SFCrimes_DimFact.tbl_curated_crime manual__2023-11-24T22:13:04.587401+00:00 [queued]>
[2023-11-26T01:26:01.907+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_SFCrimes_DimFact.tbl_curated_crime manual__2023-11-24T22:13:04.587401+00:00 [queued]>
[2023-11-26T01:26:01.908+0000] {taskinstance.py:1331} INFO - Starting attempt 5 of 5
[2023-11-26T01:26:01.980+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): tbl_curated_crime> on 2023-11-24 22:13:04.587401+00:00
[2023-11-26T01:26:01.990+0000] {standard_task_runner.py:57} INFO - Started process 119567 to run task
[2023-11-26T01:26:01.995+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_SFCrimes_DimFact', 'tbl_curated_crime', 'manual__2023-11-24T22:13:04.587401+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dag_sf_crimes_DimFact.py', '--cfg-path', '/tmp/tmppauifaa1']
[2023-11-26T01:26:01.999+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask tbl_curated_crime
[2023-11-26T01:26:02.148+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_SFCrimes_DimFact.tbl_curated_crime manual__2023-11-24T22:13:04.587401+00:00 [running]> on host jarvis
[2023-11-26T01:26:02.668+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_SFCrimes_DimFact' AIRFLOW_CTX_TASK_ID='tbl_curated_crime' AIRFLOW_CTX_EXECUTION_DATE='2023-11-24T22:13:04.587401+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-24T22:13:04.587401+00:00'
[2023-11-26T01:26:02.670+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-11-26T01:26:02.671+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/mani-dev/.local/bin/dbt run --select "tag:tbl_curated_crime" --profiles-dir /home/mani-dev/airflow/dags/dbt/dataengineering/profiles --project-dir /home/mani-dev/airflow/dags/dbt/dataengineering']
[2023-11-26T01:26:02.691+0000] {subprocess.py:86} INFO - Output:
[2023-11-26T01:26:10.527+0000] {subprocess.py:93} INFO - [0m01:26:10  Running with dbt=1.7.2
[2023-11-26T01:26:12.758+0000] {subprocess.py:93} INFO - [0m01:26:12  [[33mWARNING[0m]: Deprecated functionality
[2023-11-26T01:26:12.759+0000] {subprocess.py:93} INFO - The `source-paths` config has been renamed to `model-paths`. Please update your
[2023-11-26T01:26:12.760+0000] {subprocess.py:93} INFO - `dbt_project.yml` configuration to reflect this change.
[2023-11-26T01:26:12.763+0000] {subprocess.py:93} INFO - [0m01:26:12  [[33mWARNING[0m]: Deprecated functionality
[2023-11-26T01:26:12.763+0000] {subprocess.py:93} INFO - The `data-paths` config has been renamed to `seed-paths`. Please update your
[2023-11-26T01:26:12.763+0000] {subprocess.py:93} INFO - `dbt_project.yml` configuration to reflect this change.
[2023-11-26T01:26:13.695+0000] {subprocess.py:93} INFO - [0m01:26:13  Registered adapter: bigquery=1.7.2
[2023-11-26T01:26:13.844+0000] {subprocess.py:93} INFO - [0m01:26:13  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2023-11-26T01:26:13.845+0000] {subprocess.py:93} INFO - There are 5 unused configuration paths:
[2023-11-26T01:26:13.846+0000] {subprocess.py:93} INFO - - models.bigquery.core.semantic
[2023-11-26T01:26:13.846+0000] {subprocess.py:93} INFO - - models.bigquery.core.curated
[2023-11-26T01:26:13.847+0000] {subprocess.py:93} INFO - - models.bigquery.core.raw
[2023-11-26T01:26:13.848+0000] {subprocess.py:93} INFO - - models.bigquery
[2023-11-26T01:26:13.849+0000] {subprocess.py:93} INFO - - models.bigquery.ephemeral
[2023-11-26T01:26:13.899+0000] {subprocess.py:93} INFO - [0m01:26:13  Found 1 model, 1 source, 0 exposures, 0 metrics, 447 macros, 0 groups, 0 semantic models
[2023-11-26T01:26:13.906+0000] {subprocess.py:93} INFO - [0m01:26:13
[2023-11-26T01:28:24.957+0000] {subprocess.py:93} INFO - [0m01:28:24  Concurrency: 4 threads (target='bq')
[2023-11-26T01:28:24.959+0000] {subprocess.py:93} INFO - [0m01:28:24
[2023-11-26T01:28:24.973+0000] {subprocess.py:93} INFO - [0m01:28:24  1 of 1 START sql incremental model SFCrimeData.tbl_curated_crime ............... [RUN]
[2023-11-26T01:28:31.423+0000] {subprocess.py:93} INFO - [0m01:28:31  BigQuery adapter: https://console.cloud.google.com/bigquery?project=hakoona-matata-298704&j=bq:US:e995dcc0-359a-4016-aaa0-3bfee0fab24e&page=queryresults
[2023-11-26T01:28:31.459+0000] {subprocess.py:93} INFO - [0m01:28:31  1 of 1 ERROR creating sql incremental model SFCrimeData.tbl_curated_crime ...... [[31mERROR[0m in 6.48s]
[2023-11-26T01:28:31.479+0000] {subprocess.py:93} INFO - [0m01:28:31
[2023-11-26T01:28:31.482+0000] {subprocess.py:93} INFO - [0m01:28:31  Finished running 1 incremental model in 0 hours 2 minutes and 17.57 seconds (137.57s).
[2023-11-26T01:28:31.533+0000] {subprocess.py:93} INFO - [0m01:28:31
[2023-11-26T01:28:31.536+0000] {subprocess.py:93} INFO - [0m01:28:31  [31mCompleted with 1 error and 0 warnings:[0m
[2023-11-26T01:28:31.538+0000] {subprocess.py:93} INFO - [0m01:28:31
[2023-11-26T01:28:31.540+0000] {subprocess.py:93} INFO - [0m01:28:31    Database Error in model tbl_curated_crime (models/bigquery/core/curated/tbl_curated_crime.sql)
[2023-11-26T01:28:31.541+0000] {subprocess.py:93} INFO -   No matching signature for function PARSE_TIMESTAMP for argument types: STRING, TIMESTAMP. Supported signature: PARSE_TIMESTAMP(STRING, STRING, [STRING]) at [17:5]
[2023-11-26T01:28:31.541+0000] {subprocess.py:93} INFO -   compiled Code at target/run/dbt_framework/models/bigquery/core/curated/tbl_curated_crime.sql
[2023-11-26T01:28:31.542+0000] {subprocess.py:93} INFO - [0m01:28:31
[2023-11-26T01:28:31.544+0000] {subprocess.py:93} INFO - [0m01:28:31  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2023-11-26T01:28:33.238+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-26T01:28:33.276+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-26T01:28:33.285+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=dag_SFCrimes_DimFact, task_id=tbl_curated_crime, execution_date=20231124T221304, start_date=20231126T012601, end_date=20231126T012833
[2023-11-26T01:28:33.362+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 33 for task tbl_curated_crime (Bash command failed. The command returned a non-zero exit code 1.; 119567)
[2023-11-26T01:28:33.409+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-11-26T01:28:33.465+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
