[2023-12-04T21:02:57.596+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task manual__2023-12-04T20:57:15.277838+00:00 [queued]>
[2023-12-04T21:02:57.627+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task manual__2023-12-04T20:57:15.277838+00:00 [queued]>
[2023-12-04T21:02:57.628+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 2
[2023-12-04T21:02:57.702+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): load_to_bq_task> on 2023-12-04 20:57:15.277838+00:00
[2023-12-04T21:02:57.712+0000] {standard_task_runner.py:57} INFO - Started process 968045 to run task
[2023-12-04T21:02:57.718+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_SFCrimes_data_bqload', 'load_to_bq_task', 'manual__2023-12-04T20:57:15.277838+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/dag_sf_crimes_bqload.py', '--cfg-path', '/tmp/tmpynum_n5b']
[2023-12-04T21:02:57.723+0000] {standard_task_runner.py:85} INFO - Job 117: Subtask load_to_bq_task
[2023-12-04T21:02:57.875+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task manual__2023-12-04T20:57:15.277838+00:00 [running]> on host jarvis
[2023-12-04T21:02:58.371+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_SFCrimes_data_bqload' AIRFLOW_CTX_TASK_ID='load_to_bq_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-04T20:57:15.277838+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-04T20:57:15.277838+00:00'
[2023-12-04T21:02:59.770+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mani-dev/airflow/dags/dag_sf_crimes_bqload.py", line 19, in load_bq_raw
    source_file = Variable.get("SFcrimes_RawFiles")+'/' + Variable.get('SFcrimes_'+tail)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable SFcrimes_20231204 does not exist'
[2023-12-04T21:02:59.803+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=dag_SFCrimes_data_bqload, task_id=load_to_bq_task, execution_date=20231204T205715, start_date=20231204T210257, end_date=20231204T210259
[2023-12-04T21:02:59.879+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 117 for task load_to_bq_task ('Variable SFcrimes_20231204 does not exist'; 968045)
[2023-12-04T21:02:59.943+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-12-04T21:03:00.023+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
