[2023-11-26T01:24:50.171+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_SFCrimes_DimFact.tbl_curated_crime manual__2023-11-26T01:24:45.572558+00:00 [queued]>
[2023-11-26T01:24:50.201+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_SFCrimes_DimFact.tbl_curated_crime manual__2023-11-26T01:24:45.572558+00:00 [queued]>
[2023-11-26T01:24:50.202+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-11-26T01:24:50.279+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): tbl_curated_crime> on 2023-11-26 01:24:45.572558+00:00
[2023-11-26T01:24:50.289+0000] {standard_task_runner.py:57} INFO - Started process 119470 to run task
[2023-11-26T01:24:50.295+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_SFCrimes_DimFact', 'tbl_curated_crime', 'manual__2023-11-26T01:24:45.572558+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dag_sf_crimes_DimFact.py', '--cfg-path', '/tmp/tmpq0p75f3c']
[2023-11-26T01:24:50.300+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask tbl_curated_crime
[2023-11-26T01:24:50.451+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_SFCrimes_DimFact.tbl_curated_crime manual__2023-11-26T01:24:45.572558+00:00 [running]> on host jarvis
[2023-11-26T01:24:50.958+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_SFCrimes_DimFact' AIRFLOW_CTX_TASK_ID='tbl_curated_crime' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T01:24:45.572558+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-26T01:24:45.572558+00:00'
[2023-11-26T01:24:50.960+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-11-26T01:24:50.961+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/mani-dev/.local/bin/dbt run --select "tag:tbl_curated_crime" --profiles-dir /home/mani-dev/airflow/dags/dbt/dataengineering/profiles --project-dir /home/mani-dev/airflow/dags/dbt/dataengineering']
[2023-11-26T01:24:50.981+0000] {subprocess.py:86} INFO - Output:
[2023-11-26T01:24:58.797+0000] {subprocess.py:93} INFO - [0m01:24:58  Running with dbt=1.7.2
[2023-11-26T01:25:01.047+0000] {subprocess.py:93} INFO - [0m01:25:01  [[33mWARNING[0m]: Deprecated functionality
[2023-11-26T01:25:01.048+0000] {subprocess.py:93} INFO - The `source-paths` config has been renamed to `model-paths`. Please update your
[2023-11-26T01:25:01.048+0000] {subprocess.py:93} INFO - `dbt_project.yml` configuration to reflect this change.
[2023-11-26T01:25:01.051+0000] {subprocess.py:93} INFO - [0m01:25:01  [[33mWARNING[0m]: Deprecated functionality
[2023-11-26T01:25:01.052+0000] {subprocess.py:93} INFO - The `data-paths` config has been renamed to `seed-paths`. Please update your
[2023-11-26T01:25:01.053+0000] {subprocess.py:93} INFO - `dbt_project.yml` configuration to reflect this change.
[2023-11-26T01:25:01.970+0000] {subprocess.py:93} INFO - [0m01:25:01  Registered adapter: bigquery=1.7.2
[2023-11-26T01:25:02.115+0000] {subprocess.py:93} INFO - [0m01:25:02  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2023-11-26T01:25:02.116+0000] {subprocess.py:93} INFO - There are 5 unused configuration paths:
[2023-11-26T01:25:02.116+0000] {subprocess.py:93} INFO - - models.bigquery.core.curated
[2023-11-26T01:25:02.117+0000] {subprocess.py:93} INFO - - models.bigquery.core.semantic
[2023-11-26T01:25:02.117+0000] {subprocess.py:93} INFO - - models.bigquery.core.raw
[2023-11-26T01:25:02.118+0000] {subprocess.py:93} INFO - - models.bigquery.ephemeral
[2023-11-26T01:25:02.118+0000] {subprocess.py:93} INFO - - models.bigquery
[2023-11-26T01:25:02.169+0000] {subprocess.py:93} INFO - [0m01:25:02  Found 1 model, 1 source, 0 exposures, 0 metrics, 447 macros, 0 groups, 0 semantic models
[2023-11-26T01:25:02.176+0000] {subprocess.py:93} INFO - [0m01:25:02
[2023-11-26T01:27:13.353+0000] {subprocess.py:93} INFO - [0m01:27:13  Concurrency: 4 threads (target='bq')
[2023-11-26T01:27:13.354+0000] {subprocess.py:93} INFO - [0m01:27:13
[2023-11-26T01:27:13.370+0000] {subprocess.py:93} INFO - [0m01:27:13  1 of 1 START sql incremental model SFCrimeData.tbl_curated_crime ............... [RUN]
[2023-11-26T01:27:20.152+0000] {subprocess.py:93} INFO - [0m01:27:20  BigQuery adapter: https://console.cloud.google.com/bigquery?project=hakoona-matata-298704&j=bq:US:37cbb0af-331b-4838-8aa9-07adaec1c3c2&page=queryresults
[2023-11-26T01:27:20.186+0000] {subprocess.py:93} INFO - [0m01:27:20  1 of 1 ERROR creating sql incremental model SFCrimeData.tbl_curated_crime ...... [[31mERROR[0m in 6.81s]
[2023-11-26T01:27:20.208+0000] {subprocess.py:93} INFO - [0m01:27:20
[2023-11-26T01:27:20.211+0000] {subprocess.py:93} INFO - [0m01:27:20  Finished running 1 incremental model in 0 hours 2 minutes and 18.03 seconds (138.03s).
[2023-11-26T01:27:20.265+0000] {subprocess.py:93} INFO - [0m01:27:20
[2023-11-26T01:27:20.267+0000] {subprocess.py:93} INFO - [0m01:27:20  [31mCompleted with 1 error and 0 warnings:[0m
[2023-11-26T01:27:20.270+0000] {subprocess.py:93} INFO - [0m01:27:20
[2023-11-26T01:27:20.273+0000] {subprocess.py:93} INFO - [0m01:27:20    Database Error in model tbl_curated_crime (models/bigquery/core/curated/tbl_curated_crime.sql)
[2023-11-26T01:27:20.274+0000] {subprocess.py:93} INFO -   No matching signature for function PARSE_TIMESTAMP for argument types: STRING, TIMESTAMP. Supported signature: PARSE_TIMESTAMP(STRING, STRING, [STRING]) at [17:5]
[2023-11-26T01:27:20.274+0000] {subprocess.py:93} INFO -   compiled Code at target/run/dbt_framework/models/bigquery/core/curated/tbl_curated_crime.sql
[2023-11-26T01:27:20.277+0000] {subprocess.py:93} INFO - [0m01:27:20
[2023-11-26T01:27:20.283+0000] {subprocess.py:93} INFO - [0m01:27:20  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2023-11-26T01:27:21.924+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-26T01:27:21.960+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-26T01:27:21.969+0000] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_SFCrimes_DimFact, task_id=tbl_curated_crime, execution_date=20231126T012445, start_date=20231126T012450, end_date=20231126T012721
[2023-11-26T01:27:22.045+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 32 for task tbl_curated_crime (Bash command failed. The command returned a non-zero exit code 1.; 119470)
[2023-11-26T01:27:22.095+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-11-26T01:27:22.157+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
