[2023-12-03T09:50:36.806+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task manual__2023-12-03T09:38:45.080919+00:00 [queued]>
[2023-12-03T09:50:36.837+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task manual__2023-12-03T09:38:45.080919+00:00 [queued]>
[2023-12-03T09:50:36.838+0000] {taskinstance.py:1331} INFO - Starting attempt 3 of 3
[2023-12-03T09:50:36.908+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): load_to_bq_task> on 2023-12-03 09:38:45.080919+00:00
[2023-12-03T09:50:36.919+0000] {standard_task_runner.py:57} INFO - Started process 594529 to run task
[2023-12-03T09:50:36.925+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_SFCrimes_data_bqload', 'load_to_bq_task', 'manual__2023-12-03T09:38:45.080919+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/dag_sf_crimes_bqload.py', '--cfg-path', '/tmp/tmp5e1fgm2y']
[2023-12-03T09:50:36.929+0000] {standard_task_runner.py:85} INFO - Job 94: Subtask load_to_bq_task
[2023-12-03T09:50:37.086+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task manual__2023-12-03T09:38:45.080919+00:00 [running]> on host jarvis
[2023-12-03T09:50:37.585+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_SFCrimes_data_bqload' AIRFLOW_CTX_TASK_ID='load_to_bq_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-03T09:38:45.080919+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-03T09:38:45.080919+00:00'
[2023-12-03T09:50:38.985+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mani-dev/airflow/dags/dag_sf_crimes_bqload.py", line 24, in load_bq_raw
    autodetect=Flase,
NameError: name 'Flase' is not defined
[2023-12-03T09:50:39.017+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=dag_SFCrimes_data_bqload, task_id=load_to_bq_task, execution_date=20231203T093845, start_date=20231203T095036, end_date=20231203T095039
[2023-12-03T09:50:39.097+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 94 for task load_to_bq_task (name 'Flase' is not defined; 594529)
[2023-12-03T09:50:39.152+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-12-03T09:50:39.232+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
