[2023-11-24T17:05:05.189+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_SFCrimes_data_download.download_data_task scheduled__2023-11-24T05:00:00+00:00 [queued]>
[2023-11-24T17:05:05.219+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_SFCrimes_data_download.download_data_task scheduled__2023-11-24T05:00:00+00:00 [queued]>
[2023-11-24T17:05:05.220+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 2
[2023-11-24T17:05:05.294+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): download_data_task> on 2023-11-24 05:00:00+00:00
[2023-11-24T17:05:05.303+0000] {standard_task_runner.py:57} INFO - Started process 50611 to run task
[2023-11-24T17:05:05.308+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_SFCrimes_data_download', 'download_data_task', 'scheduled__2023-11-24T05:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/curated/dag_sf_crimes_raw.py', '--cfg-path', '/tmp/tmpdoq2qh2u']
[2023-11-24T17:05:05.313+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask download_data_task
[2023-11-24T17:05:05.469+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_SFCrimes_data_download.download_data_task scheduled__2023-11-24T05:00:00+00:00 [running]> on host jarvis
[2023-11-24T17:05:05.996+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_SFCrimes_data_download' AIRFLOW_CTX_TASK_ID='download_data_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-24T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-24T05:00:00+00:00'
[2023-11-24T17:05:06.735+0000] {socrata.py:63} WARNING - Requests made without an app_token will be subject to strict throttling limits.
[2023-11-24T17:05:07.913+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mani-dev/airflow/dags/curated/dag_sf_crimes_raw.py", line 30, in download_data
    dest_file = Variable.get("SFcrimes_RawFiles")+'/SFcrimes_'+tail+'.csv'
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable SFcrimes_RawFiles does not exist'
[2023-11-24T17:05:07.944+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=dag_SFCrimes_data_download, task_id=download_data_task, execution_date=20231124T050000, start_date=20231124T170505, end_date=20231124T170507
[2023-11-24T17:05:08.020+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task download_data_task ('Variable SFcrimes_RawFiles does not exist'; 50611)
[2023-11-24T17:05:08.059+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-11-24T17:05:08.136+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
