[2023-12-03T09:19:29.210+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task manual__2023-12-03T08:30:20.826070+00:00 [queued]>
[2023-12-03T09:19:29.251+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task manual__2023-12-03T08:30:20.826070+00:00 [queued]>
[2023-12-03T09:19:29.252+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-12-03T09:19:29.301+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): load_to_bq_task> on 2023-12-03 08:30:20.826070+00:00
[2023-12-03T09:19:29.329+0000] {standard_task_runner.py:57} INFO - Started process 588537 to run task
[2023-12-03T09:19:29.337+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_SFCrimes_data_bqload', 'load_to_bq_task', 'manual__2023-12-03T08:30:20.826070+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/dag_sf_crimes_bqload.py', '--cfg-path', '/tmp/tmppmlv7xym']
[2023-12-03T09:19:29.347+0000] {standard_task_runner.py:85} INFO - Job 84: Subtask load_to_bq_task
[2023-12-03T09:19:29.657+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task manual__2023-12-03T08:30:20.826070+00:00 [running]> on host jarvis
[2023-12-03T09:19:30.415+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_SFCrimes_data_bqload' AIRFLOW_CTX_TASK_ID='load_to_bq_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-03T08:30:20.826070+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-03T08:30:20.826070+00:00'
[2023-12-03T09:19:32.086+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mani-dev/airflow/dags/dag_sf_crimes_bqload.py", line 16, in load_bq_raw
    tail = now.strftime("%Y%m%d")
NameError: name 'now' is not defined
[2023-12-03T09:19:32.152+0000] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_SFCrimes_data_bqload, task_id=load_to_bq_task, execution_date=20231203T083020, start_date=20231203T091929, end_date=20231203T091932
[2023-12-03T09:19:32.241+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 84 for task load_to_bq_task (name 'now' is not defined; 588537)
[2023-12-03T09:19:32.292+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-12-03T09:19:32.422+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
